# Recover the jar from the parent image
# Use the latest image built as this is what is under test
FROM hbpmip/data-db-setup as parent-image

# Build stage for Java classes
FROM maven:3.5.2-jdk-8-alpine as build-java-env

COPY --from=parent-image /usr/share/jars/data-db-setup.jar /flyway/jars/
COPY src/main/java/ /project/src/

WORKDIR /project/src
RUN jar uvf /flyway/jars/data-db-setup.jar -C . .

# Final image
# Use the latest image built as this is what is under test
FROM hbpmip/data-db-setup

ARG BUILD_DATE
ARG VCS_REF
ARG VERSION

COPY --from=build-java-env /flyway/jars/data-db-setup.jar /flyway/jars/data-db-setup.jar
COPY sql/V1_0__create.sql /flyway/sql/V1_0__create.sql
COPY sql/data_A.csv sql/data_B.csv /data/

ENV IMAGE=joined-tables \
    DATASETS=testA,testB \
    VIEWS=sample_join
