# Final image
# Use the latest image built as this is what is under test
FROM hbpmip/data-db-setup

ARG BUILD_DATE
ARG VCS_REF
ARG VERSION

COPY config/ /flyway/config/
COPY sql/V1_0__create.sql /flyway/sql/
COPY sql/data_A.csv sql/data_B.csv /data/

ENV IMAGE=joined-tables \
    DATASETS=testA,testB \
    VIEWS=sample_join
